name: gas-cylinder-monitor
icon: ⚖️
description: "LPG gas cylinder weight monitor"
ports: [7000]
bricks:
  - arduino:web_ui: {}
network_mode: "host"
sockets:
  - "/run/dbus/system_bus_socket:/run/dbus/system_bus_socket"
